### ISSUE TITLE
About the env installation

### ISSUE THREAD

**Issue by yangguangjie** [ying09/TextFuseNet.pytorch#103]
helle, if i can use the cuda11 to run the code? I only have the rtx3090 , which don't support the cuda101. I try to use the cuda111 and torch1.8.
when I run "python setup.py build develop" ,it error like following?how can i solve it?thanks.
Traceback (most recent call last):
  File "setup.py", line 85, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/command/build.py", line 24, in run
    super().run()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 554, in build_extension
    depends=ext.depends,
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/ygj/anaconda3/envs/torch_cuda11/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by tobiasraidl** [comment]
I have the same problem rn. Any solutions?

**Comment by prajeet26** [comment]
> I have the same problem rn. Any solutions?

hey would love to know if you got any work around!
