### ISSUE TITLE
TypeError: cannot unpack non-iterable VisImage object

### ISSUE THREAD

**Issue by dadizak** [ying09/TextFuseNet.pytorch#84]
thanks for this work,i'm very gratefuly to help me to fix this error:
Traceback (most recent call last):
  File "/content/TextFuseNet/demo/icdar2015_detection.py", line 135, in <module>
    prediction, vis_output, polygons = detection_demo.run_on_image(img)
  File "/content/TextFuseNet/demo/predictor.py", line 64, in run_on_image
    vis_output, polygons = visualizer.draw_instance_predictions(predictions=instances)
TypeError: cannot unpack non-iterable VisImage object

**Comment by mwolf2** [comment]
Hi, I encountered the same error running icdar2015_detection.py. I suspect it might be something to do with the fact that I am not running TextFuseNet-Detectron due to CUDA 10.1 being incompatible with my GPU but here's the fix that is working for me right now:

In icdar2015_detection.py, change line 135 from
`prediction, vis_output, polygons = detection_demo.run_on_image(img)`
to
`prediction, vis_output = detection_demo.run_on_image(img)`
and comment out line 139.

Then, in predictor.py, change line 64 from
`vis_output,polygons = visualizer.draw_instance_predictions(predictions=instances)`
to
`vis_output = visualizer.draw_instance_predictions(predictions=instances)`
and comment out `, polygons` in line 66.

My guess is that their TextFuseNet-detectron's visualizer function works differently than the one in stock Detectron2. Hope this helps.

**Comment by angrylau** [comment]
**pip uninstall detectron2**
**uninstall detectron2**
in TextFuseNet folder：
**python setup.py install**
**pip install fvcore-master.zip**

**Comment by angrylau** [comment]
> pip uninstall detectron2

> conda uninstall detectron2

in TextFuseNet folder：

> python setup.py install

> pip install fvcore-master.zip

**Comment by scry-yewenzhou** [comment]
> Hi, I encountered the same error running icdar2015_detection.py. I suspect it might be something to do with the fact that I am not running TextFuseNet-Detectron due to CUDA 10.1 being incompatible with my GPU but here's the fix that is working for me right now:
> 
> In icdar2015_detection.py, change line 135 from `prediction, vis_output, polygons = detection_demo.run_on_image(img)` to `prediction, vis_output = detection_demo.run_on_image(img)` and comment out line 139.
> 
> Then, in predictor.py, change line 64 from `vis_output,polygons = visualizer.draw_instance_predictions(predictions=instances)` to `vis_output = visualizer.draw_instance_predictions(predictions=instances)` and comment out `, polygons` in line 66.
> 
> My guess is that their TextFuseNet-detectron's visualizer function works differently than the one in stock Detectron2. Hope this helps.

There would still be problems in save_result_to_txt as it takes in polygons as an argument.

**Comment by Hegelim** [comment]
> Hi, I encountered the same error running icdar2015_detection.py. I suspect it might be something to do with the fact that I am not running TextFuseNet-Detectron due to CUDA 10.1 being incompatible with my GPU but here's the fix that is working for me right now:
> 
> In icdar2015_detection.py, change line 135 from `prediction, vis_output, polygons = detection_demo.run_on_image(img)` to `prediction, vis_output = detection_demo.run_on_image(img)` and comment out line 139.
> 
> Then, in predictor.py, change line 64 from `vis_output,polygons = visualizer.draw_instance_predictions(predictions=instances)` to `vis_output = visualizer.draw_instance_predictions(predictions=instances)` and comment out `, polygons` in line 66.
> 
> My guess is that their TextFuseNet-detectron's visualizer function works differently than the one in stock Detectron2. Hope this helps.

There would still be problems in save_result_to_txt as it takes in polygons as an argument
